#!/bin/bash
SECRET_KEY=$(python -c 'import random; import string; print "".join([random.SystemRandom().choice(string.digits + string.letters) for i in range(150)])')

cat <<EOF > /etc/graphite/local_settings.py
SECRET_KEY = '${SECRET_KEY}'
TIME_ZONE = 'Europe/London'
USE_REMOTE_USER_AUTHENTICATION = True
LOG_RENDERING_PERFORMANCE = True
LOG_CACHE_PERFORMANCE = True
LOG_METRIC_ACCESS = True
GRAPHITE_ROOT = '/usr/share/graphite-web'
CONF_DIR = '/etc/graphite'
STORAGE_DIR = '/data/graphite/whisper'
WHISPER_DIR = '/data/graphite/whisper'
CONTENT_DIR = '/usr/share/graphite-web/static'
LOG_DIR = '/data/logs/graphite'
INDEX_FILE = '/data/graphite/search_index'  # Search index file
DATABASES = {
    'default': {
        'NAME': '/data/graphite/graphite.db',
        'ENGINE': 'django.db.backends.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': ''
    }
}
EOF
ls -l /
graphite-manage syncdb --noinput
