version: '2'
services:
  ubuntu-graphite-grafana:
    build: .
    image: 1and1internet/ubuntu-graphite-grafana
    user: "100000"
    ports:
      - "2003:2003"
      - "8080:8080"
    environment:
      - "SUPERVISORD_EXIT_ON_FATAL=0"
